### PR TITLE
Add new modal-dialog behavior code

### PR DESCRIPTION
**Pull request by owenniblock**
# Motivation

After discussions around Accessibility and dialogs - we're suggesting the following changes:

## Modal Dialog Behavior

- [x] Overflow is hidden when dialog is open
- [x] Uses the new focusTrap code (must always contain a focusable element)

I have added some [handover notes as a comment](https://github.com/primer/behaviors/pull/48#issuecomment-1075280378)

### CODE REVIEW

**Comment by langermank** [comment]
I know the `behaviors` package is still new so there might not be guidelines for this yet- but will this specific behavioral TS ship with the PVC component? Or is it expected that dotcom will take a dependency on `behaviors` and import this piece of logic directly?

**Comment by owenniblock** [comment]
@langermank long-term it's my understanding that we'll roll the compiled TypeScript up in the the PVC JavaScript output (like you can see here in the corresponding PVC draft PR: https://github.com/primer/view_components/pull/985/files#diff-a7fe811b096a8daf7e33675fb92e09c979fdd884bf04385d52ad5f063ed0ce09R1)

I say long-term since we're about to move the dialog code to the dotcom code as an experimental view component so we can validate our work and check for edge cases that we haven't covered with the current API (we already have a couple around lazy-loading we know we'll need to look at).

I'm not sure yet how we'll be temporarily including the behaviors code - I'll try to work that out over the next few days.

**Comment by langermank** [comment]
> long-term it's my understanding that we'll roll the compiled TypeScript up in the the PVC JavaScript output 

Excellent! That would be my preference 😄 

> I'm not sure yet how we'll be temporarily including the behaviors code - I'll try to work that out over the next few days.

I think in this case it makes sense to follow what was done for `<action-list>` https://github.com/github/github/tree/master/app/components/primer/action_list

**Comment by owenniblock** [comment]
### Handover Notes

I have copied the code back from dotcom (when the dialog is upstreamed to Primer we will need to remove the experimental component's files).

**Important:** the one change I have _not_ copied across is where we have removed `eventListenerSignalPolyfill()` (cc @keithamus who advised this change). This change is still necessary and should be done. Justification is that dotcom already includes this polyfill and library consumers should be free to choose whether and which polyfills to include when using this library.

There has been a lot of discussion around whether component code should live in this repo, whether we should use web components or not etc. I'll leave those decisions up to the team picking this up. Perhaps the behvior code could be encapsulated in this library outside of a web component (long term) and the code to utilise it as a web component could live within `primer/view_components`?

**Comment by owenniblock** [comment]
Closing this, there have been changes since I created this PR for helping upstreaming. We should recreate this PR with the code from the experimental component.

**Pull request closed without merging**
