### PR TITLE
Add observer to focus-trap

### PR DESCRIPTION
**Pull request by TylerJDev**
## Summary
Adds a mutation observer to `focus-trap` that ensures that the `sentinel` elements stay at the start/end. The observer only checks for added elements that are direct descendants of the container, meaning that children of those descendants shouldn't trigger the observer.

<hr aria-hidden="true" />

### New Tests:
* Added a test to verify that sentinel elements remain at the start and end of the inner container when new elements are added. (`src/__tests__/focus-trap.test.tsx`)
* Added a test to ensure the mutation observer is removed when the focus trap is released. (`src/__tests__/focus-trap.test.tsx`)

### Focus Trap Enhancements:
* Implemented `observeFocusTrap` function to create a `MutationObserver` that maintains sentinel elements at the correct positions. (`src/focus-trap.ts`)
* Integrated the `observeFocusTrap` function into the `focusTrap` function to observe changes in the container and reposition sentinel elements as needed. (`src/focus-trap.ts`)
* Ensured the `MutationObserver` is disconnected when the focus trap is released to prevent memory leaks. (`src/focus-trap.ts`)

### CODE REVIEW

**Comment by siddharthkp** [comment]
Let's test the canary version with https://github.com/primer/react/pull/4779 to make sure we don't have any [performance regressions](https://github.com/primer/react/pull/4779#issuecomment-2260576002)

**Comment by jonrohan** [comment]
gonna leave this review to @siddharthkp

**Comment by TylerJDev** [comment]
@siddharthkp - Looks like there shouldn't be any big performance regressions. I did not do an in-depth analysis, but I can confirm that the mutation observer should only operate under the following conditions: 

* Element was added before start sentinel
* Element was added after end sentinel
* Element is added directly as a child of `<Dialog>`
  * If a child is added to the body, footer, or header subcomponents, it won't notify the mutation observer

In either case, we only re-append the sentinel to the start/end depending on which sentinel needs to be adjusted. Curious on what you think!

https://github.com/user-attachments/assets/c39dcc9f-4324-484b-9320-e415065e20d3

**Video description**: Showcasing items being appended in `Dialog`'s body and before/after the sentinels. Shows me enabling/disabling the focus trap, ensuring the mutation observer is disconnected properly.

**Review by siddharthkp — COMMENTED** [review]
Looks good to me! 

Let's try this with PRC to test further

**Review by siddharthkp — COMMENTED** [review]
Looks good to me!

Let's try this with PRC to test further

**Review by siddharthkp — APPROVED** [review]
Let's go!

**Pull request merged**
